services:
  downloader:
    image: "cogmi_downloader:0.2.1"
    build: .
    volumes:
      - ./output:/downloader/output
      - ./temp_dir:/downloader/temp_dir
      - ./cache_dir:/downloader/cache_dir
    command:
      - --collection=BTC_postop
      - --mode=auto
      - --user=None
      - --password=None
      - --compress
      # - --bids

