name: URT
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - dcm2niix=1.0.20240202
  - pigz=2.8
  - pip=24.0
  - python=3.11.4
  - pyyaml=6.0.1
  - requests=2.32.3
  - requests-cache=1.2.0
  - synapseclient=4.1.0
  - checksumdir=1.2.0
  - pip:
      - bidscoin==4.3.0
