name: URT
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=23.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2023.7.22
  - cattrs=23.1.2
  - dcm2niix=1.0.20230411
  - exceptiongroup=1.1.3
  - icu=73.2
  - idna=3.4
  - itsdangerous=2.1.2
  - ld_impl_linux-64=2.40
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-ng=13.1.0
  - libgomp=13.1.0
  - libnsl=2.0.0
  - libsqlite=3.42.0
  - libstdcxx-ng=13.1.0
  - libuuid=2.38.1
  - libuv=1.46.0
  - libzlib=1.2.13
  - ncurses=6.4
  - nodejs=20.7.0
  - openssl=3.1.3
  - pigz=2.6
  - pip=23.1.2
  - pysocks=1.7.1
  - python=3.11.4
  - python_abi=3.11
  - pyyaml=6.0.1
  - readline=8.2
  - requests=2.31.0
  - requests-cache=1.1.0
  - setuptools=68.0.0
  - six=1.16.0
  - tk=8.6.12
  - typing-extensions=4.7.1
  - typing_extensions=4.7.1
  - ujson=5.7.0
  - url-normalize=1.4.3
  - wheel=0.40.0
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
      - asttokens==2.2.1
      - backcall==0.2.0
      - backoff==2.2.1
      - bids-validator==1.13.1
      - bidscoin==4.1.1
      - certifi==2023.5.7
      - charset-normalizer==3.1.0
      - coloredlogs==15.0.1
      - comm==0.1.3
      - contourpy==1.1.0
      - cycler==0.11.0
      - dataclasses==0.6
      - debugpy==1.6.7
      - decorator==5.1.1
      - deprecated==1.2.14
      - executing==1.2.0
      - fonttools==4.40.0
      - googleapis-common-protos==1.62.0
      - humanfriendly==10.0
      - importlib-metadata==6.11.0
      - ipykernel==6.24.0
      - ipython==8.14.0
      - ipywidgets==8.0.7
      - jedi==0.18.2
      - jsonschema==3.2.0
      - jupyter-client==8.3.0
      - jupyter-core==5.3.1
      - jupyterlab-widgets==3.0.8
      - kiwisolver==1.4.4
      - matplotlib==3.7.2
      - matplotlib-inline==0.1.6
      - multiecho==0.29
      - nest-asyncio==1.5.6
      - nibabel==5.1.0
      - numpy==1.25.0
      - opencv-python==4.8.0.76
      - opentelemetry-api==1.21.0
      - opentelemetry-exporter-otlp-proto-common==1.21.0
      - opentelemetry-exporter-otlp-proto-http==1.21.0
      - opentelemetry-proto==1.21.0
      - opentelemetry-sdk==1.21.0
      - opentelemetry-semantic-conventions==0.42b0
      - packaging==23.1
      - pandas==2.0.3
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==10.0.0
      - platformdirs==3.8.0
      - prompt-toolkit==3.0.39
      - protobuf==4.25.3
      - psutil==5.9.5
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pydicom==2.4.1
      - pydicom-seg==0.4.1
      - pygments==2.15.1
      - pyparsing==3.0.9
      - pyqt6==6.5.2
      - pyqt6-qt6==6.5.2
      - pyqt6-sip==13.5.2
      - pyrsistent==0.19.3
      - python-dateutil==2.8.2
      - pytz==2023.3
      - pyzmq==25.1.0
      - rt-utils==1.2.7
      - ruamel-yaml==0.17.32
      - ruamel-yaml-clib==0.2.7
      - simpleitk==2.2.1
      - stack-data==0.6.2
      - synapseclient==4.0.0
      - tcia-utils==1.6.9
      - tornado==6.3.2
      - tqdm==4.66.1
      - traitlets==5.9.0
      - tzdata==2023.3
      - urllib3==2.0.3
      - wcwidth==0.2.6
      - widgetsnbextension==4.0.8
      - wrapt==1.16.0
      - zipp==3.17.0