name: URT
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - attrs=23.2.0
  - backoff=2.2.1
  - backports.csv=1.0.7
  - binutils=2.40
  - binutils_impl_linux-64=2.40
  - binutils_linux-64=2.40
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.27.0
  - c-compiler=1.7.0
  - ca-certificates=2024.2.2
  - cattrs=23.2.3
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - checksumdir=1.2.0
  - compilers=1.7.0
  - cryptography=42.0.5
  - cxx-compiler=1.7.0
  - dbus=1.13.6
  - dcm2niix=1.0.20240202
  - deprecated=1.2.14
  - exceptiongroup=1.2.0
  - expat=2.5.0
  - fortran-compiler=1.7.0
  - future=1.0.0
  - gcc=12.3.0
  - gcc_impl_linux-64=12.3.0
  - gcc_linux-64=12.3.0
  - gdbm=1.18
  - gettext=0.21.1
  - gfortran=12.3.0
  - gfortran_impl_linux-64=12.3.0
  - gfortran_linux-64=12.3.0
  - gmp=6.3.0
  - googleapis-common-protos=1.62.0
  - grpcio=1.61.1
  - gxx=12.3.0
  - gxx_impl_linux-64=12.3.0
  - gxx_linux-64=12.3.0
  - idna=3.6
  - importlib-metadata=6.10.0
  - itsdangerous=2.1.2
  - jaraco.classes=3.3.1
  - jeepney=0.8.0
  - kernel-headers_linux-64=2.6.32
  - keyring=24.3.0
  - ld_impl_linux-64=2.40
  - libabseil=20240116.1
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgcc-devel_linux-64=12.3.0
  - libgcc-ng=13.2.0
  - libgfortran5=13.2.0
  - libglib=2.78.4
  - libgomp=13.2.0
  - libgrpc=1.61.1
  - libiconv=1.17
  - libnsl=2.0.1
  - libprotobuf=4.25.2
  - libre2-11=2023.09.01
  - libsanitizer=12.3.0
  - libsqlite=3.45.1
  - libstdcxx-devel_linux-64=12.3.0
  - libstdcxx-ng=13.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.2.13
  - more-itertools=10.2.0
  - ncurses=6.4
  - openssl=3.2.1
  - opentelemetry-api=1.23.0
  - opentelemetry-exporter-otlp=1.23.0
  - opentelemetry-exporter-otlp-proto-common=1.23.0
  - opentelemetry-exporter-otlp-proto-grpc=1.23.0
  - opentelemetry-exporter-otlp-proto-http=1.23.0
  - opentelemetry-proto=1.23.0
  - opentelemetry-sdk=1.23.0
  - opentelemetry-semantic-conventions=0.44b0
  - pcre2=10.42
  - pigz=2.8
  - pip=24.0
  - platformdirs=4.2.0
  - protobuf=4.25.2
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.2
  - python_abi=3.12
  - pyyaml=6.0.1
  - re2=2023.09.01
  - readline=8.2
  - requests=2.31.0
  - requests-cache=1.2.0
  - ruby=3.2.2
  - secretstorage=3.3.3
  - setuptools=69.1.1
  - six=1.16.0
  - synapseclient=4.1.0
  - sysroot_linux-64=2.12
  - tk=8.6.13
  - typing-extensions=4.10.0
  - typing_extensions=4.10.0
  - ujson=5.9.0
  - url-normalize=1.4.3
  - urllib3=1.26.18
  - wheel=0.42.0
  - wrapt=1.16.0
  - xz=5.2.6
  - yaml=0.2.5
  - zipp=3.17.0
  - pip:
      - bids-validator==1.14.1
      - bidscoin==4.3.0
      - citeproc-py==0.6.0
      - coloredlogs==15.0.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - drmaa==0.7.9
      - duecredit==0.9.3
      - fonttools==4.49.0
      - humanfriendly==10.0
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - kiwisolver==1.4.5
      - lxml==5.1.0
      - matplotlib==3.8.3
      - multiecho==0.29
      - nibabel==5.2.1
      - numpy==1.26.4
      - packaging==23.2
      - pandas==2.2.1
      - pillow==10.2.0
      - pydicom==2.4.4
      - pyparsing==3.1.1
      - pyqt6==6.6.1
      - pyqt6-qt6==6.6.2
      - pyqt6-sip==13.6.0
      - python-dateutil==2.8.2
      - pytz==2024.1
      - referencing==0.33.0
      - rpds-py==0.18.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - tqdm==4.66.2
      - tzdata==2024.1
